### ISSUE TITLE
How to do Sticky Header? How to make a cell not draggable? 

### ISSUE THREAD

**Issue by JulianSwales** [DevOrbiter/drag_and_drop_gridview#2]
Is there a way to add a sticky header to the columns? I see a header option, but doesn't seem to do anything, and what I'd like is a header that sticks for each column as the user scrolls down the table of cells..

Also I'd like to be able to turn off certain cells from being draggable. How is this possible? 
Two reasons for this.. I'd like the first column to indicate what row the users is on as the scroll down a long list, but clear don't want that cell draggable, and second, some of the other grid cells I'd like to turn off from being draggable.. 

Thanks.

**Comment by IshanJaiswal99** [comment]
Greetings,
Thank you for reaching out to us. We have looked into the matter and found that the header option was not working as intended, so we fixed it and will be releasing it in the next couple of days along with the feature to make a child unmoveable/undraggable.

Could you please however explain what did you mean by a sticky header of columns in the gridview widget of flutter. If I am not wrong then maybe you are talking about the Table Widget of flutter. Kindly help me out with an illustration or may a code snippet if possible it would help a lot. Thanks

**Comment by JulianSwales** [comment]
I am wanting a Table design...  I was looking for a drag and drop table,  columns along the top with rows down the side but that had each cell in the table potentially draggable to any other.  All the drag and drop table solutions I've found drag the row but not down at the cell level.. Your drag drop grid view was the closest I found..  And so far it's been working. but as the grid scrolls, I'd like a header row that sticks.. I was looking at creating just a row at the top, with this Grid View below it.. But thought I'd ask about the sticky header such that it lined up with the grid columns as part of the widget.. I had thought that the header widget was maybe going to do that, but then didn't see it being used, so wasn't sure what the header widget was intended for..  
So, yes, I'm attempting to use this Grid View as a Table, with each cell of the table potentially draggable to any other. 
Thanks.

**Comment by IshanJaiswal99** [comment]
Thank you for your response. We looked into the matter and would be happy to let you know that we are already working on a custom table widget for Flutter. However, the result that you are trying to achieve is out of the scope of our drag and drop gridview, I would request you to hold tight as the drag and drop table widget is on its way scheduled to be launched in the next couple of days.
Thanks.

**Comment by IshanJaiswal99** [comment]
Hi, I would like to inform you that we have added many variations of drag and drop sticky headers. You may have a look into it. Thank you.
