### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by robertoltrocha** [DevOrbiter/drag_and_drop_gridview#4]
Hi,

Is it possible to customize the widget(change the background color for exemple, change the size ....) when hovering over a widget?

thanks

**Comment by IshanJaiswal99** [comment]
Hi,

I am sure if I fully understand your query. You can change the background, size, etc using a container as a wrapper of this widget. However, if you want to change the style of the "Child" while hovering over  you may wanna have a look into:

https://github.com/DevOrbiter/drag_and_drop_gridview#example-9-draganddropgridview-change-child
you can pass your custom widget in "childWhenDragging".

Also, you may have a look over here:
https://github.com/DevOrbiter/drag_and_drop_gridview#example-10-draganddropgridview-change-feedback
you can pass your custom widget in "feedback"

If the above doesn't help, please let us know what feature you want and we will surely look into it.

Thanks

**Comment by robertoltrocha** [comment]
It is exactly i´m looking for.
thank you.
