### ISSUE TITLE
isDraggable: false disallows drop

### ISSUE THREAD

**Issue by JulianSwales** [DevOrbiter/drag_and_drop_gridview#5]
When I add DragItem and set isDraggable: false I then can't drag it (good in my use case) and I can't drop on it (bad in my use case).  
I have a use case where I have items to drag to and drop on other items that themselves are not draggable.  
I have three use cases in my situation: 

1. Item is draggable and drobonable
2. Item is not draggable but is droponable
3. Item is not draggable and not droponable

BTW Thanks for the Sticky headers. They work very well.. 

Two documentation updates. 
Example 6 where you introduce DragItem you have DrarItem
Also you should indicate that you need to include drag.dart to get DragItem. 

Thanks.

**Comment by debashisnandy** [comment]
Thank you for your feedback. We will work on this and release a new update as soon as possible.

**Comment by IshanJaiswal99** [comment]
Hi,

Thank you for reaching out to us with your query. We have added a new parameter in `DragItem` called `isDropable`, by default it is set to **true** allowing you to achieve the result that you want,
i.e. 

1) when `isDraggable = true` & `isDropable = true` you are allowed to drag and drop child in that spot.

2) When you pass `isDraggable = false` but want to accept drops on that spot and it will accept the drop on that spot.

3) when `isDraggable = false` & `isDropable = false` you are not allowed to either drag or drop the child in that spot.

**Note:** If you want to validate drop on a specific spot please take advantage of the `OnWillAccept` function.

I hope it solves all of your scenarios. If there is any doubt feel free to reach out to us.

**Comment by mrLIHUAN** [comment]
GridView.builder 中没有这个dragStartBehavior属性

**Comment by IshanJaiswal99** [comment]
@mrLIHUAN I am sorry but we can not understand what you are trying to say. We only understand English.

Thank you
