### ISSUE TITLE
dragStartBehavior

### ISSUE THREAD

**Issue by mrLIHUAN** [DevOrbiter/drag_and_drop_gridview#6]
GridView.builder  Found this candidate, but the arguments don't match. dragStartBehavior

**Comment by debashisnandy** [comment]
I'm sorry I'm unable to understand your problem. It will be helpful if you explain your problem properly. If Possible attach some screenshot to get a more clear view of the problem.

**Comment by mrLIHUAN** [comment]
There is no such property in GridView.builder dragStartBehavior

**Comment by debashisnandy** [comment]
This plugin is all about DragAndDropGridView. And also if you are using the GridView.builder please refer to this [Flutter Official Documentation](https://api.flutter.dev/flutter/widgets/GridView/GridView.builder.html).

**Comment by mrLIHUAN** [comment]
Which version of Flutter are you using

**Comment by debashisnandy** [comment]
Flutter Channel beta, 1.21.0-9.2.pre

**Comment by mrLIHUAN** [comment]
Is it a new attribute added by Flutter?
